name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Please answer the following questions for yourself before submitting an issue.
      options:
      - label: I have searched [the existing issues]((https://github.com/epam/epam-graphql/issues)
      - label: I checked the documentation and found no answer
      - label: I checked to make sure that this issue has not already been filed
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Please describe the behavior you are expecting
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
         "# Current Behavior"
         Please describe the behavior you are expecting
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps for reproducing the issue. Provide screenshots or minimal code snippet where appropriate.
      value: | 
        "1. step 1"
        "2. step 2"
        "3. you get it..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
      value: | 
        "* Package versions"
        "*.Operating System"
