name: Build

on:
  push:
    branches: main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore solution
      run: dotnet restore
    - name: Build solution [Release]
      run: dotnet build --no-restore -c Release -p:Version=$ref
    - name: Test
      run: dotnet test --no-build --configuration Release
  pack:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
    - name: Pack solution [Release]
      run: dotnet pack --no-restore -c Release -p:Version=$ref -o out
    - uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts
  